language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
script:
- npm run build:full
after_script:
- cat ./coverage/lcov.info | coveralls
env:
  global:
  - secure: DogYopZFhZLYQ7ldDslUgY+z02abOQoWfPNAUr9DILDq5gcwrECXYGnoXjHeUsY/llhCKkbf9E1pfkMttVEcrsPE3QOd6lrxrigUb4rWG/zOn6PTO+hKAYQmXZboWaeNV50KME4w3eaW8xhueyaIQUrcq9Ete87WYusuQgk9ETK60V5Zq7oL0tD1XMpsGELfoyuQMW8EwnRy4xMv3FB5gY8ddgg75OkjWlLKGP/N2cbRRgI4pm7Mkwr90gH0ryXFXOt9cTHkrDbpBevI2pnheD/O3cEIFl6eNMnqcANfc9tHAyYqeqgukM+e1nZKIUaMFSQt6H5cGkSsUDqJOihmT0LXxq5tD4Vnl4bPnycXQIjP2sq9XIlR9bGH8wz7useqTESwnXdbQfsL6ZtMGhkv1jLbhadVByIEfbAyVdbeeRMsBrqEjzcwIRZFxbBQhNwjsDijzG9PYBUIACuoZb9tGKkHtOVNo0tMoyAy+Xzg+9qeGi/hJjWmVHG8+xXG82SVNOx1VEksE5JIHlDa/N7/DTVJ6l0PAs18UHhqtjwfZNhR6Y6Nxn7/9ldGliP+iUz4hb55p0u0J4toLM/UhWVXKfPKPwSEszzZHDJNf6dEmA5BPRXGB6nj6ju+XqDuF7ezaCmpMlC0ZXnuQWZOzzW1JYDpjPDBWaO+eucOSoYGcs4=
  - secure: ifHlDxEBTxtgHtqC4uS8cqn+XZPBOTk7HDe5cVAYQniwT5S0P/eO3HgsiNBZoYsjzx/DCAMSgFfoNshbKTvKzfgseqH8o8v+9XWBNmKolScFAERbCmWGWH3xwQqOUn+8gpmshdPlVWT0WxTEtzmrx8NT2mr9bFtjkUf81DUCJQL4S9TTEJcOMaf6HjTOPcpDWoFMTGxDtv7ziQebe+oDDx3XLOzCBjavAf6sUVH6JhKuVQRuqrxnVN6Oqc4x/6FOzsepAUGGO9wUj3XlSf6D8REyQuW1OaepMTzyeMIfwIZsSBcg92STgCKYGkEqWzwg2/n8J53cUB8kpwgsgSo6r8Bmph2gEZ+S0W80yUNljss3mc5Xdz08aLkiKsjeL4s9nOik1T/m6OcmStNLZ6VXxwdfo3jdK/UIXwWpTsZLH2OkLgwRsVJ0br88V4jwfUMi7CPV5WwwBV/oy0R4RmcaaYeRJD9D/4oXs/otad/qXat0NuQdCxtudJZCU8LHahH+uViLe8knlRzEr3yoL8+ZMQOWVYLufepdHBRuNdPeDLa/Q6MB2Hvwf2lfJH8CeSqcpEKvCl2FFtuPj43lNj2skw4wxc/D1yMmx/Lh10UT90VjkVrZNHoj8G3gz5fD1GI9YJDvPkDjwncZT21RIPTP3GGRCbqt0GkdYgjBqcfk2Qk=
